package geektext;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.PathVariable;

@Controller // This means that this class is a Controller
@RequestMapping(path="/user") // This means URIs start with /user (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@GetMapping(path="/all")
	@ResponseBody // This returns a JSON or XML with the users
	public Iterable<User> getAllUsers() {
		return userRepository.findAll();
	}
	
	@GetMapping(path="/{id}")
	@ResponseBody // This returns a JSON or XML of a single user by id
	public User getUser(@PathVariable Integer id) {
	    return userRepository.findById(id).orElseThrow(() -> new UserNotFoundException(id)); 
	    // i do this instead of using java optional so that some msg is returned on usernotfound exception 
	    // also this gives a 404 im not sure if java optional gave a 404
	}
}